from database_orm import SessionLocal
from models import Author, Book

session = SessionLocal()

# # Create an author object. This does NOT insert into the database yet.
# # It just creates a Python object in memory.
# author = Author(name="Navneet Singh", country="UK",
#                 bio="Bestseller author from India")

# # add() stages the object for insertion. Like adding an item to
# # the shopping cart. Still not in the database.
# session.add(author)

# # commit() actually executes the INSERT statement and saves to the database.
# # After this, the author has an id (auto-generated by the database).
# session.commit()

# print(author.id)    # 1 -- the database assigned this ID
# print(author.name)  # "Arundhati Roy"


session = SessionLocal()

# # You can add multiple objects at once
# authors = [
#     Author(name="Chetan Bhagat", country="India"),
#     Author(name="Ruskin Bond", country="India",
#            bio="Master of short stories"),
#     Author(name="Amish Tripathi", country="India",
#            bio="Author of the Shiva Trilogy"),
# ]

# # add_all() stages multiple objects at once
# session.add_all(authors)
# session.commit()


# Now let us add books for these authors
# books = [
#     Book(title="The God of Small Things", author_id=1, price=350, pages=321),
#     Book(title="Five Point Someone", author_id=2, price=199, pages=270),
#     Book(title="The Room on the Roof", author_id=3, price=175, pages=192),
#     Book(title="The Blue Umbrella", author_id=3, price=150, pages=80),
#     Book(title="The Immortals of Meluha", author_id=4, price=299, pages=408),
#     Book(title="The Secret of the Nagas", author_id=4, price=299, pages=375),
# ]

# session.add_all(books)
# session.commit()



## Update some record

# book = session.query(Book).filter(Book.title == "Five Point Someone").first()
# print(book, book.id, book.title)

# book.price = 250
# session.commit()

# session.rollback() ## this will undo all the changes made in that session
# session.close() # this will close the connection from the database


# session = SessionLocal()

# try:
#     book = session.query(Book).filter(Book.title == "Five Point Someone").first()
#     print(book, book.id, book.title)

#     book.price = 250
#     session.commit()

# except:
#     session.rollback()
# else:
#     print("Transaction success!")
# finally:
#     session.close()



## Get all the authors ( select * from authors )
# all_authors = session.query(Author).all()
# print(all_authors)

# for author in all_authors:
#     print(author.name)

# [Author(id=1, name='Arundhati Roy'), Author(id=2, name='Navneet Singh'), Author(
#     id=3, name='Chetan Bhagat'), Author(id=4, name='Ruskin Bond'), Author(id=5, name='Amish Tripathi')]


# Get Books cheaper than 200 rupees
cheap_books = session.query(Book).filter(Book.price<200)
print([book.title for book in cheap_books])

# ['The Room on the Roof', 'The Blue Umbrella']

## Get book where price is less than 500 but pages more than 200
filtered = session.query(Book).filter(
    Book.price < 500,
    Book.pages > 200
).all()

for book in filtered:
    print(book.title, book.price, book.pages)

# The God of Small Things 350.0 321
# Five Point Someone 250.0 270
# The Immortals of Meluha 299.0 408
# The Secret of the Nagas 299.0 375


# Order by price ascending
my_books = session.query(Book).order_by(Book.price.asc()).all()
print([(book.title, book.price) for book in  my_books])

# [('The Blue Umbrella', 150.0), ('The Room on the Roof', 175.0), ('Five Point Someone', 250.0),
#  ('The Immortals of Meluha', 299.0), ('The Secret of the Nagas', 299.0), ('The God of Small Things', 350.0)]


# [Book(id=4, title='The Blue Umbrella'), Book(id=3, title='The Room on the Roof'), Book(id=2, title='Five Point Someone'), Book(
#     id=5, title='The Immortals of Meluha'), Book(id=6, title='The Secret of the Nagas'), Book(id=1, title='The God of Small Things')]



## aggregation
### count all books
from sqlalchemy import func
count = session.query(func.count(Book.id)).scalar()
print(count)

avg_price = session.query(func.avg(Book.price)).scalar()
print(f"Average price: {avg_price}")

# Count books per author
# author_wise_count = session.query(Book.author_id, func.count(Book.id)).group_by(Book.author_id).all()
# print(author_wise_count)

# for record in author_wise_count:
#     author = session.query(Author).get(record[0])
#     print(author.name, author.id)
# Arundhati Roy 1
# Navneet Singh 2
# Chetan Bhagat 3
# Ruskin Bond 4
# [(1, 1), (2, 1), (3, 2), (4, 2)]




## Relationships
# book = session.query(Book).get(1) # filter on primary key book_id
# print(book.id, book.title, book.author_id)
# author = session.query(Author).get(book.author_id)
# print(author)



## Delete a record

wrong_author = session.query(Author).filter(Author.id == 7).first()
print(wrong_author)

# wrong_books = wrong_author.books
# print(wrong_books)


session.delete(wrong_author)
session.commit()


